version: "3"

services:
  app:
    container_name: app
    build: .
    command: npm run dev
    ports:
      - "6800:6800"
    env_file:
      - .env
    volumes:
      - .:/usr/app
  app-macon-db:
    container_name: macon-db-mssql
    restart: always
    image: mcr.microsoft.com/mssql-tools
    ports:
      - "1433:1433"
    env_file:
      - .env
    environment:
      SA_PASSWORD: "google.2021"
      ACCEPT_EULA: "Y"
networks:
  network:
    name: macon-network


